name: 'Print Delombok'
description: 'Print Delomboked source files'
inputs:
  delombokSourcePath:
    description: 'Path relative to workspace directory where the Delomboked source files are'
    required: false
    default: src-delombok

runs:
  using: "composite"
  steps:
    - run: |
        echo "Action path: ${{ github.action_path }}"
        echo "Inputs:"
        echo "  directory: ${{ inputs.delombokSourcePath }}"
        echo "---- Start of Delomboked source files ----"
        if [ -d "${{ inputs.delombokSourcePath }}" ]; then find "${{ inputs.delombokSourcePath }}" -type f -print -exec cat -n {} \; ; else echo "No delomboked sources found. Directory '${{ inputs.delombokSourcePath }}' does not exist." ; fi
        echo "---- End of Delomboked source files ----"
      shell: bash
